# Generated by Django 3.2.12 on 2024-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20240419_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fulfillment',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], max_length=100),
        ),
    ]
